[workspace]
resolver = "2"
members = [
  "expression-core",
  "expression-js",
  "expression-ruby/ext/lago_expression",
  "expression-go",
]

[profile.release]
lto = true

[profile.release.package.lago-expression]
opt-level = 's'
