[package]
name = "expression-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bigdecimal = "0.4.5"
lazy_static = "1.5.0"
pest = "2.7.13"
pest_derive = "2.7.13"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
thiserror = "1.0.64"
