[package]
name = "expression-go"
version = "0.1.3"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
expression-core = { path = '../expression-core' }
serde_json = "1.0.132"

[build-dependencies]
cbindgen = "0.27"
