name: Ruby

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./expression-ruby
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: rake compile
      - name: Run tests
        run: rake spec
